-- 简历档案扩展：姓名/电话/邮箱/学历/工作经历/技能/证书（小程序简历表单字段）
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS name TEXT NOT NULL DEFAULT '';
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS phone TEXT NOT NULL DEFAULT '';
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS email TEXT NOT NULL DEFAULT '';
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS education TEXT NOT NULL DEFAULT '';
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS work_experience TEXT NOT NULL DEFAULT '';
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS skills TEXT NOT NULL DEFAULT '[]';
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS certificate_url TEXT NOT NULL DEFAULT '';
