-- 企业档案扩展：信用代码/法人/电话/产业分类/规模/地址/简介（小程序入驻表单字段）
ALTER TABLE enterprises ADD COLUMN IF NOT EXISTS credit_code TEXT NOT NULL DEFAULT '';
ALTER TABLE enterprises ADD COLUMN IF NOT EXISTS legal_person TEXT NOT NULL DEFAULT '';
ALTER TABLE enterprises ADD COLUMN IF NOT EXISTS contact_phone TEXT NOT NULL DEFAULT '';
ALTER TABLE enterprises ADD COLUMN IF NOT EXISTS industry_category TEXT NOT NULL DEFAULT '';
ALTER TABLE enterprises ADD COLUMN IF NOT EXISTS scale TEXT NOT NULL DEFAULT '';
ALTER TABLE enterprises ADD COLUMN IF NOT EXISTS address TEXT NOT NULL DEFAULT '';
ALTER TABLE enterprises ADD COLUMN IF NOT EXISTS description TEXT NOT NULL DEFAULT '';
