-- 品牌展示扩展：分类/行业筛选、精选位(featured)、认证标志(verified)、视频与浏览计数
ALTER TABLE member_portfolios ADD COLUMN IF NOT EXISTS category TEXT NOT NULL DEFAULT '';
ALTER TABLE member_portfolios ADD COLUMN IF NOT EXISTS industry TEXT NOT NULL DEFAULT '';
ALTER TABLE member_portfolios ADD COLUMN IF NOT EXISTS verified BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE member_portfolios ADD COLUMN IF NOT EXISTS video_url TEXT NOT NULL DEFAULT '';
ALTER TABLE member_portfolios ADD COLUMN IF NOT EXISTS video_count INTEGER NOT NULL DEFAULT 0;
ALTER TABLE member_portfolios ADD COLUMN IF NOT EXISTS views INTEGER NOT NULL DEFAULT 0;
ALTER TABLE member_portfolios ADD COLUMN IF NOT EXISTS featured BOOLEAN NOT NULL DEFAULT FALSE;
