ALTER TABLE resumes DROP COLUMN IF EXISTS certificate_url;
ALTER TABLE resumes DROP COLUMN IF EXISTS skills;
ALTER TABLE resumes DROP COLUMN IF EXISTS work_experience;
ALTER TABLE resumes DROP COLUMN IF EXISTS education;
ALTER TABLE resumes DROP COLUMN IF EXISTS email;
ALTER TABLE resumes DROP COLUMN IF EXISTS phone;
ALTER TABLE resumes DROP COLUMN IF EXISTS name;
