-- 服务能力初始数据（供需大厅服务侧展示，分类对齐小程序 巡检/航拍/测绘/应急）
INSERT INTO service_listings (
    id, provider_id, provider_name, title, category, description, region, price_fen, unit, image, status, created_at, updated_at
) VALUES
('sl-1', 'enterprise-yihang', '重庆翼航科技',
 '桥梁与光伏设施精细化巡检',
 '巡检',
 '提供可见光、热成像、倾斜摄影和缺陷报告一体化巡检服务。团队配置多旋翼行业机和持证飞手，可支持紧急响应。',
 '重庆及周边', 150000, '项', '', 'published', NOW(), NOW()),
('sl-2', 'enterprise-feiyue', '重庆飞越传媒',
 '企业宣传航拍与 4K 成片制作',
 '航拍',
 '企业园区、活动、文旅场景的航拍和后期制作。提供合规飞行方案、4K 成片和基础调色。',
 '重庆 · 两江新区', 8000, '次', '', 'published', NOW(), NOW()),
('sl-3', 'enterprise-cehui', '成都苍穹测绘',
 '三维实景建模与地形测绘',
 '测绘',
 '倾斜摄影三维建模、地形测量与断面测绘，交付 DOM/DEM/实景三维模型，可配合项目申报。',
 '川渝地区', 120000, '平方公里', '', 'published', NOW(), NOW()),
('sl-4', 'enterprise-jijiu', '重庆山城应急救援队',
 '应急搜救与物资投送支援',
 '应急',
 '具备搜救类多旋翼与抛投载荷能力，24 小时值班响应，配合应急管理部门执行搜救、物资投送与灾后巡查任务。',
 '重庆全域', 20000, '次', '', 'published', NOW(), NOW()),
('sl-5', 'enterprise-nongye', '重庆农飞植保合作社',
 '丘陵地区植保飞防作业',
 '植保',
 '面向柑橘、水稻等作物的植保飞防作业，自有 T60 植保机 12 台，经验丰富，支持药剂配比建议。',
 '重庆 · 奉节县', 80000, '亩', '', 'published', NOW(), NOW()),
('sl-6', 'enterprise-sun', '重庆翼航科技',
 '电力线路无人机带电巡检',
 '巡检',
 '持有电力巡检资质，可开展输电线路可见光与红外带电巡检，交付缺陷台账与影像报告，服务过 2000 公里线路。',
 '重庆及西南', 90000, '公里', '', 'published', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;
