// ============================================================
// 品牌展示 · 演示数据（mock）
// ------------------------------------------------------------
// 【接口替换点】后端就绪后：
//   列表：GET /api/v1/portfolios  (params: page / page_size)
//   我的品牌：GET /api/v1/portfolios/mine
//   创建/更新：POST /api/v1/portfolios、PUT /api/v1/portfolios/{id}
// 页面已在 list.vue / detail.vue / mine.vue / edit.vue 中标注替换位置（搜索“接口替换点”）。
// 字段约定遵循后端 snake_case，前端组件做优雅降级映射。
// ============================================================

// 分类 key → 中文
// ⚠️ 必须与平台统一术语一致：utils/enums.js ENTERPRISE_CATEGORY_LABEL（企业产业分类）
// 页面禁止另立类型 map；新增类型先改后端标准，再同步本文件与 enums.js。
export const CATEGORY_MAP = {
  drone: '整机',
  part: '零部件',
  flight_ctrl: '飞控',
  payload: '载荷',
  operator: '运营服务',
  college: '实训院校',
  airport: '通航机场',
  inspector: '检测机构',
}

// 封面渐变（前端占位视觉，真实数据用 cover_url / images 字段替换）
export const GRAD_CLASS = {
  gd1: 'gd-1',
  gd2: 'gd-2',
  gd3: 'gd-3',
  gd4: 'gd-4',
  gd5: 'gd-5',
  gd6: 'gd-6',
  gd7: 'gd-7',
  gd8: 'gd-8',
}

export const MOCK_BRANDS = [
  {
    id: 'demo-zongshen',
    name: '重庆宗申航空发动机',
    category: 'drone',
    char: '造',
    logo_text: '宗',
    verified: true,
    is_vip: true,
    featured: true,
    has_video: true,
    views: 2300,
    video_count: 3,
    case_count: 12,
    grad: 'gd1',
    desc: '国内领先的航空活塞发动机及无人机动力系统制造商，产品覆盖 30-180kW 动力平台，服务全球 40 余家整机厂商，深耕低空经济动力赛道十余年。',
    fields: ['航空动力系统', '无人机发动机', '动力配套'],
    location: '重庆市巴南区 · 宗申工业园',
    founded: '2016年 · 会员年限 8 年',
    certs: ['高新技术企业', 'ISO9001', 'AS9100D'],
    products: ['ZS-60 航空活塞发动机', '30-180kW 无人机动力平台', 'ZS-120 高原型发动机', '油电混动动力单元'],
    honors: ['国家高新技术企业', '专精特新中小企业', 'ISO9001 质量体系', 'AS9100D 航空体系', '低空经济领军企业'],
    video_list: [
      { title: '宗申动力 · 低空制造宣传片', duration: '03:24', grad: 'gd1' },
      { title: '无人机发动机产线探访', duration: '02:48', grad: 'gd2' },
      { title: '2026 新品发布实录', duration: '05:12', grad: 'gd4' },
      { title: '国际合作 · 品牌故事', duration: '04:05', grad: 'gd5' },
    ],
    cases: [
      { title: '西南地区万亩级无人机植保动力升级', tag: '农业植保', meta: '2026 · 36 台套', grad: 'gd1' },
      { title: '山火巡查无人机动力保障项目', tag: '应急救援', meta: '2025 · 20 台套', grad: 'gd2' },
      { title: '城市低空物流无人机动力平台', tag: '低空物流', meta: '2026 · 12 台套', grad: 'gd4' },
    ],
  },
  {
    id: 'demo-yunzhiyi',
    name: '云之翼通用航空',
    category: 'operator',
    char: '运',
    logo_text: '云',
    verified: true,
    featured: false,
    has_video: true,
    views: 1800,
    video_count: 2,
    case_count: 8,
    grad: 'gd2',
    desc: '专注低空物流与无人机运营服务的通用航空企业，拥有 CCAR-91 运营资质，提供支线配送、应急投送等场景化运营解决方案。',
    fields: ['低空物流', '无人机运营', '应急投送'],
    location: '重庆市两江新区 · 航空产业园',
    founded: '2018年 · 会员年限 5 年',
    certs: ['CCAR-91 运营资质', '高新技术企业'],
    products: ['支线物流无人机运营', '应急物资投送方案', '冷链生鲜配送航线'],
    honors: ['CCAR-91 运营资质', '高新技术企业'],
    video_list: [
      { title: '云之翼 · 低空物流解决方案', duration: '02:35', grad: 'gd2' },
      { title: '城市配送航线实拍', duration: '03:10', grad: 'gd8' },
    ],
    cases: [
      { title: '重庆主城生鲜冷链无人机配送试点', tag: '低空物流', meta: '2026 · 12 条航线', grad: 'gd2' },
      { title: '山区应急物资投送保障', tag: '应急救援', meta: '2025 · 30 架次', grad: 'gd8' },
    ],
  },
  {
    id: 'demo-cqu',
    name: '重庆大学飞行器研究院',
    category: 'college',
    char: '研',
    logo_text: '飞',
    verified: true,
    featured: true,
    has_video: true,
    views: 1600,
    video_count: 4,
    case_count: 15,
    grad: 'gd4',
    desc: '依托重庆大学航空宇航学科，开展飞行器总体设计、智能控制与低空安全研究，承担国家级科研项目 20 余项，面向产业输出关键技术。',
    fields: ['飞行器设计', '智能控制', '低空安全'],
    location: '重庆市沙坪坝区 · 重庆大学',
    founded: '2015年 · 会员年限 8 年',
    certs: ['国家级科研平台', '重点实验室'],
    products: ['飞行器总体设计方案', '智能飞控算法平台', '低空安全评估体系'],
    honors: ['国家级科研平台', '重点实验室'],
    video_list: [
      { title: '实验室开放日 · 飞行器研发', duration: '04:12', grad: 'gd4' },
      { title: '低空安全课题成果展', duration: '03:08', grad: 'gd1' },
    ],
    cases: [
      { title: '山地无人机应急救援关键技术', tag: '科研攻关', meta: '2025 · 国家课题', grad: 'gd4' },
      { title: '城市低空航线安全评估体系', tag: '标准研制', meta: '2026 · 团体标准', grad: 'gd1' },
    ],
  },
  {
    id: 'demo-jingwei',
    name: '精微无人机科技',
    category: 'part',
    char: '零',
    logo_text: '精',
    verified: true,
    featured: false,
    has_video: false,
    views: 986,
    video_count: 1,
    case_count: 6,
    grad: 'gd5',
    desc: '无人机精密零部件供应商，主营碳纤维结构件、精密传动与传感器模组，为西南地区整机厂商提供配套服务。',
    fields: ['碳纤维结构件', '精密传动', '传感器模组'],
    location: '重庆市九龙坡区 · 高端制造园',
    founded: '2019年 · 会员年限 4 年',
    certs: ['ISO9001', '专精特新企业'],
    products: ['碳纤维机身结构件', '精密传动组件', '传感器模组'],
    honors: ['ISO9001', '专精特新企业'],
    video_list: [],
    cases: [
      { title: '轻量化机身结构件批量供应', tag: '整机配套', meta: '2026 · 3000 套', grad: 'gd5' },
    ],
  },
  {
    id: 'demo-yundong',
    name: '两江云动科技',
    category: 'operator',
    char: '动',
    logo_text: '云',
    verified: true,
    featured: false,
    has_video: true,
    views: 842,
    video_count: 2,
    case_count: 5,
    grad: 'gd3',
    desc: '聚焦无人机巡检服务与数据平台，为电力、管网、交通等行业提供标准化巡检方案与 AI 缺陷识别服务。',
    fields: ['无人机巡检', 'AI 缺陷识别', '数据平台'],
    location: '重庆市两江新区 · 数字经济产业园',
    founded: '2020年 · 会员年限 3 年',
    certs: ['高新技术企业'],
    products: ['电力巡检服务', '管网巡检方案', 'AI 缺陷识别平台'],
    honors: ['高新技术企业'],
    video_list: [
      { title: '电力巡检示范应用', duration: '02:20', grad: 'gd3' },
      { title: 'AI 识别平台演示', duration: '01:55', grad: 'gd7' },
    ],
    cases: [
      { title: '川渝输电网无人机巡检服务', tag: '电力巡检', meta: '2026 · 800km', grad: 'gd3' },
    ],
  },
  {
    id: 'demo-feiyu',
    name: '飞宇智能装备',
    category: 'drone',
    char: '智',
    logo_text: '飞',
    verified: false,
    featured: false,
    has_video: false,
    views: 521,
    video_count: 0,
    case_count: 3,
    grad: 'gd7',
    desc: '工业级无人机整机及智能挂载装备制造商，主打测绘、应急行业机型，认证审核中。',
    fields: ['工业无人机', '智能挂载', '测绘装备'],
    location: '重庆市北碚区 · 智能装备园',
    founded: '2021年 · 会员年限 2 年',
    certs: [],
    products: ['工业级测绘无人机', '应急行业机型', '智能挂载装备'],
    honors: [],
    video_list: [],
    cases: [],
  },
  {
    id: 'demo-bashan',
    name: '巴山通用航空',
    category: 'airport',
    char: '台',
    logo_text: '巴',
    verified: true,
    featured: false,
    has_video: true,
    views: 438,
    video_count: 1,
    case_count: 4,
    grad: 'gd8',
    desc: '低空经济综合服务平台运营商，提供空域协调、飞行保障、人才培训等一站式服务，服务会员单位 60 余家。',
    fields: ['综合服务', '飞行保障', '人才培训'],
    location: '重庆市渝北区 · 龙兴通用机场',
    founded: '2017年 · 会员年限 6 年',
    certs: ['通用航空运营资质'],
    products: ['空域协调服务', '飞行保障方案', '人才培训服务'],
    honors: ['通用航空运营资质'],
    video_list: [
      { title: '龙兴机场 · 综合保障纪实', duration: '03:40', grad: 'gd8' },
    ],
    cases: [
      { title: '会员单位联合飞行保障计划', tag: '飞行保障', meta: '2026 · 60 家', grad: 'gd8' },
    ],
  },
  {
    id: 'demo-sanxia',
    name: '三峡无人机学院',
    category: 'college',
    char: '学',
    logo_text: '三',
    verified: true,
    featured: false,
    has_video: true,
    views: 367,
    video_count: 3,
    case_count: 7,
    grad: 'gd6',
    desc: '面向产业输送无人机驾驶员与维保人才的培训机构，拥有 CAAC 认证培训资质，累计培养持证飞手 2000+。',
    fields: ['驾驶员培训', '维保人才', 'CAAC 认证'],
    location: '重庆市万州区 · 三峡职教园',
    founded: '2019年 · 会员年限 4 年',
    certs: ['CAAC 认证培训资质'],
    products: ['无人机驾驶员培训', '维保人才培训', '企业定制实训'],
    honors: ['CAAC 认证培训资质'],
    video_list: [
      { title: '培训基地一日纪实', duration: '02:58', grad: 'gd6' },
      { title: '学员实训现场', duration: '01:47', grad: 'gd1' },
    ],
    cases: [
      { title: '政企联合飞手培养计划', tag: '人才培养', meta: '2026 · 300 人', grad: 'gd6' },
    ],
  },
]

// 精选横幅数据（运营推荐，接口替换点：列表接口 featured=true 或独立推荐位接口）
export const MOCK_FEATURED = [
  { id: 'demo-zongshen', tag: '精选推荐', name: '重庆宗申航空发动机', sub: '整机 · 航空动力领军企业', grad: 'gd1', has_video: true },
  { id: 'demo-cqu', tag: '会员专访', name: '重庆大学飞行器研究院', sub: '实训院校 · 前沿飞行器技术', grad: 'gd4', has_video: true },
  { id: 'demo-yunzhiyi', tag: '精选推荐', name: '云之翼通用航空', sub: '运营服务 · 低空物流解决方案', grad: 'gd2', has_video: false },
]
